---
- project:
    templates:
      - ansible-python-jobs
    check:
      jobs:
        - ansible-network-iosxr-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-iosxr-appliance/.*
        ## ansible-test* roles
        - build-ansible-collection:
            required-projects:
              - name: github.com/ansible-collections/openvswitch.openvswitch
              - name: github.com/ansible-collections/amazon.aws
              - name: github.com/ansible-collections/ansible.netcommon
              - name: github.com/ansible-collections/community.vmware
            files:
              - roles/vmware.*
              - roles/ansible-test*
              - playbooks/ansible-cloud/.*
        - ansible-test-units-openvswitch-python38:
            files:
              - roles/ansible-test*
        - ansible-test-cloud-integration-vcenter7_only-python36:
            match-on-config-updates: false
            files:
              - roles/vmware.*
              - roles/ansible-test*
              - playbooks/ansible-cloud/.*
            vars:
              ansible_test_integration_targets: vmware_vcenter_settings
        - ansible-test-network-integration-openvswitch-python35:
            match-on-config-updates: false
            files:
              - roles/ansible-test*
            vars:
              ansible_test_collections: true

    gate:
      jobs:
        - ansible-network-iosxr-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-iosxr-appliance/.*
        ## ansible-test* roles
        - build-ansible-collection:
            required-projects:
              - name: github.com/ansible-collections/openvswitch.openvswitch
              - name: github.com/ansible-collections/amazon.aws
              - name: github.com/ansible-collections/ansible.netcommon
              - name: github.com/ansible-collections/community.vmware
            files:
              - roles/vmware.*
              - roles/ansible-test*
              - playbooks/ansible-cloud/.*
        - ansible-test-units-openvswitch-python38:
            files:
              - roles/ansible-test*
        - ansible-test-cloud-integration-vcenter7_only-python36:
            match-on-config-updates: false
            files:
              - roles/vmware.*
              - roles/ansible-test*
              - playbooks/ansible-cloud/.*
            vars:
              ansible_test_integration_targets: vmware_vcenter_settings
        - ansible-test-network-integration-openvswitch-python35:
            match-on-config-updates: false
            files:
              - roles/ansible-test*
            vars:
              ansible_test_collections: true
