---
- project:
    templates:
      - ansible-python-jobs
    check:
      jobs:
        - ansible-network-eos-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-eos-appliance/.*
    gate:
      jobs:
        - ansible-network-eos-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-eos-appliance/.*
