---
- hosts: controller
  tasks:
    - name: Ensure tox
      include_role:
        name: ensure-tox

    - name: Setup tox role
      include_role:
        name: tox
      vars:
        tox_envlist: venv
        tox_extra_args: -vv -- ansible-playbook -v -c network_cli playbooks/ansible-security-trendmicro-deepsec-appliance/files/bootstrap.yaml
        tox_install_siblings: false
        zuul_work_dir: "{{ zuul.projects['github.com/ansible/ansible-zuul-jobs'].src_dir }}"

    - name: Install PostgreSQL
      become: true
      package: name={{ item }} state=present
      with_items:
        - postgresql
        - postgresql-contrib
        - libpq-dev
        - python-psycopg2

    - name: Ensure the PostgreSQL service is running
      service: name=postgresql state=started enabled=yes

    - name: Install deep security services
      become: true
      package: name={{ item }} state=present
      with_items:
        - ds_agent
        - dsm_s

    - name: Ensure the DS services are running
      service: name={{ item }} state=started enabled=yes
      with_items:
        - ds_agent
        - dsm_s
